version: "2"
stack_defaults:
  runner_image: gberntg/spacelift-twingate:latest
  before_init:
    - "echo \"$TWINGATE_SERVICE_KEY\" > /etc/twingate/service_key.json"
    - "echo >>> Service key written"
    - "echo >>> Starting Twingate client..."
    - "twingated --http-proxy 0.0.0.0:9999 --tun off &"
    - "sleep 15"
    - "echo >>> Twingate client started"
    - "echo >>> Starting proxytunnel..."
    - "proxytunnel --standalone=5432 --proxy=127.0.0.1:9999 --dest=$DB_DEST &"
    - "sleep 3"
    - "echo >>> proxytunnel started"
    - "echo >>> Checking if tunnel is up..."
    - "pg_isready -h 127.0.0.1 -p 5432 || echo tunnel not ready yet"
